function generateRandomItems() {
    var items = [
        albums = [
            "487\tBlack Flag\tSST",
            "483\tThe Anthology\tMuddy Waters",
            "482\tBizzare Ride II the Pharcyde\tThe Pharcyde",
            "480\tThe Weight of These Wings\tMiranda Lambert",
            "479\tAmor Prohibido\tSelena",
            "478\tSomething Else by the Kinks\tThe Kinks",
            "477\tMoanin' in the Moonlight\tHowlin' Wolf",
            "476\tKimono My House\tSparks",
            "475\tSheryl Crow\tSheryl Crow",
            "474\t#1 Record\tBig Star",
            "473\tBarrio Fino\tDaddy Yankee",
            "472\tCtrl\tSZA",
            "471\tSurrealistic Pillow\tJefferson Airplane",
            "470\t400 Degreez\tJuvenile",
            "469\tClandestino\tManu Chao",
            "468\tSome Girls\tThe Rolling Stones",
            "467\tBLACKsummers'night\tMaxwell",
            "466\tThe Beach Boys Today!\tThe Beach Boys",
            "465\tThe Best of the Classic Years\tKing Sunny Ade",
            "464\t3+3\tThe Isley Brothers",
            "463\tEli & the 13th Confession\tLaura Nyro",
            "462\tThe Gilded Palace of Sin\tThe Flying Burrito Brothers",
            "460\tMelodrama\tLorde",
            "459\tMan on the Moon: The End of the Day\tKid Cudi",
            "458\tSoutheastern\tJason Isbell",
            "457\tI Do Not Want What I Haven't Got\tSinead O'Connor",
            "456\tGreatest Hits\tAl Green",
            "455\tBo Diddley/ Go Bo Diddley\tBo Diddley",
            "454\tEge Bamyasi\tCan",
            "453\tPretty Hate Machine\tNine Inch Nails",
            "452\tAnthology\tDiana Ross and the Supremes",
            "451\tFirst Take\tRoberta Flack",
            "450\tRam\tPaul and Linda McCartney",
            "449\tElephant\tThe White Stripes",
            "448\tDictionary of Soul\tOtis Redding",
            "447\tX 100pre\tBad Bunny",
            "446\tJourney in Satchidanada\tAlice Coltrane",
            "445\tClose to the Edge\tYes",
            "444\tExtraordinary Machine\tFiona Apple",
            "443\tScary Monsters\tDavid Bowie",
            "442\tBeauty Behind the Madness\tThe Weeknd",
            "441\tBlackout\tBritney Spears",
            "440\tCoal Miner's Daughter\tLoretta Lynn",
            "439\tSex Machine\tJames Brown",
            "438\tParklife\tBlur",
            "437\tScreamadelica\tPrimal Scream",
            "436\tAll Eyez on Me\t2Pac",
            "435\tActually\tPet Shop Boys",
            "433\tSound of Silver\tLCD Soundsystem",
            "432\tConfessions\tUsher",
            "431\tHow Will the Wolf Survive?\tLos Lobos",
            "430\tMy Aim is True\tElvis Costello",
            "429\tReach Out\tThe Four Tops",
            "428\tNew Day Rising\tHusker Du",
            "427\tCall Me\tAl Green",
            "426\tLucinda Williams\tLucinda Williams",
            "425\tNothing's Shocking\tJane's Addiction",
            "424\tMingus Ah Um\tCharles Mingus",
            "423\tFresh\tSly and the Family Stone",
            "422\tTwo Steps From the Blues\tBobby 'Blue' Bland",
            "421\tHeart Like a Wheel\tLinda Ronstadt",
            "420\tPearl\tJanis Joplin",
            "419\tRain Dogs\tTom Waits",
            "418\tMe Against the World\t2Pac",
            "417\tKind of Blue\tMiles Davis",
            "416\tRumours\tFleetwood Mac",
            "415\tEminem Show\tEminem",
            "414\tBad\tMichael Jackson",
            "413\tOdessey and Oracle\tThe Zombies",
            "412\tThe Trinity Session\tCowboy Junkies",
            "411\tBorn in the U.S.A.\tBruce Springsteen",
            "410\tA Night at the Opera\tQueen",
            "409\tMTV Unplugged in New York\tNirvana",
            "408\tThe Chronic\tDr. Dre",
            "407\tPost\tBjork",
            "406\tBack to Black\tAmy Winehouse",
            "405\tBand on the Run\tPaul McCartney and Wings",
            "404\tMTV Unplugged\tTony Bennett",
            "403\tCrazySexyCool\tTLC",
            "402\tThe Wild, the Innocent, and the E Street Shuffle\tBruce Springsteen",
            "401\tHelp!\tThe Beatles",
            "400\tRock Steady\tNo Doubt",
            "399\tRaw Power\tIggy and the Stooges",
            "398\tStand!\tSly and the Family Stone",
            "397\tThe Score\tThe Fugees",
            "396\tBitches Brew\tMiles Davis",
            "395\tMr. Tambourine Man\tThe Byrds",
            "394\tMusic of My Mind\tStevie Wonder",
            "393\tBaduizm\tErykah Badu",
            "392\tParallel Lines\tBlondie",
            "391\tThe Marshall Mathers LP\tEminem",
            "390\tThe Stranger\tBilly Joel",
            "389\tLive Through This\tHole",
            "388\tPurple Rain\tPrince",
            "387\tAt Last!\tEtta James",
            "386\tDaydream Nation\tSonic Youth",
            "385\tA Hard Day's Night\tThe Beatles",
            "384\tStankonia\tOutKast",
            "383\tBlood on the Tracks\tBob Dylan",
            "382\tNevermind\tNirvana",
            "381\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "380\tThe Blueprint\tJay-Z",
            "379\tIn Utero\tNirvana",
            "378\tSuperfly\tCurtis Mayfield",
            "377\tSongs in the Key of Life\tStevie Wonder",
            "376\tThe Dark Side of the Moon\tPink Floyd",
            "375\tLive at the Apollo\tJames Brown",
            "374\tPet Sounds\tThe Beach Boys",
            "373\tKind of Blue\tMiles Davis",
            "372\tBlonde on Blonde\tBob Dylan",
            "371\tLed Zeppelin IV\tLed Zeppelin",
            "370\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "369\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "368\tBlue\tJoni Mitchell",
            "367\tDisraeli Gears\tCream",
            "366\tAppetite for Destruction\tGuns N' Roses",
            "365\tAxis: Bold as Love\tThe Jimi Hendrix Experience",
            "364\tHunky Dory\tDavid Bowie",
            "363\tVan Halen\tVan Halen",
            "362\tOK Computer\tRadiohead",
            "361\tAt Fillmore East\tThe Allman Brothers Band",
            "360\tAfter the Gold Rush\tNeil Young",
            "359\tBorn to Run\tBruce Springsteen",
            "358\tWho's Next\tThe Who",
            "357\tThe Joshua Tree\tU2",
            "356\tRubber Soul\tThe Beatles",
            "355\tCourt and Spark\tJoni Mitchell",
            "354\tMaster of Puppets\tMetallica",
            "353\tElectric Ladyland\tThe Jimi Hendrix Experience",
            "352\tSign o' the Times\tPrince",
            "351\tRage Against the Machine\tRage Against the Machine",
            "350\tTommy\tThe Who",
            "349\tMoondance\tVan Morrison",
            "348\tAre You Experienced\tThe Jimi Hendrix Experience",
            "347\tPurple Rain\tPrince",
            "346\tAchtung Baby\tU2",
            "345\tSticky Fingers\tThe Rolling Stones",
            "344\tThe Doors\tThe Doors",
            "343\tBorn in the U.S.A.\tBruce Springsteen",
            "342\tParallel Lines\tBlondie",
            "341\tRamones\tRamones",
            "340\tAftermath\tThe Rolling Stones",
            "339\tBridge Over Troubled Water\tSimon and Garfunkel",
            "338\tThe Low End Theory\tA Tribe Called Quest",
            "337\tPhysical Graffiti\tLed Zeppelin",
            "336\tThe Queen Is Dead\tThe Smiths",
            "335\tAppetite for Destruction\tGuns N' Roses",
            "334\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "333\tThe Doors\tThe Doors",
            "332\tExile on Main St.\tThe Rolling Stones",
            "331\tAt Fillmore East\tThe Allman Brothers Band",
            "330\tThe Wall\tPink Floyd",
            "329\tLed Zeppelin IV\tLed Zeppelin",
            "328\tSurrealistic Pillow\tJefferson Airplane",
            "327\tRemain in Light\tTalking Heads",
            "326\tThe Dark Side of the Moon\tPink Floyd",
            "325\tDisraeli Gears\tCream",
            "324\tPet Sounds\tThe Beach Boys",
            "323\tHighway 61 Revisited\tBob Dylan",
            "322\tNevermind\tNirvana",
            "321\tLet It Bleed\tThe Rolling Stones",
            "320\tAbbey Road\tThe Beatles",
            "319\tAre You Experienced\tThe Jimi Hendrix Experience",
            "318\tRubber Soul\tThe Beatles",
            "317\tRevolver\tThe Beatles",
            "316\tLed Zeppelin II\tLed Zeppelin",
            "315\tAretha Now\tAretha Franklin",
            "314\tThe Beatles (The White Album)\tThe Beatles",
            "313\tLondon Calling\tThe Clash",
            "312\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "311\tBeggars Banquet\tThe Rolling Stones",
            "310\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "309\tThe Doors\tThe Doors",
            "308\tBlonde on Blonde\tBob Dylan",
            "307\tElectric Ladyland\tThe Jimi Hendrix Experience",
            "306\tHighway 61 Revisited\tBob Dylan",
            "305\tExile on Main St.\tThe Rolling Stones",
            "304\tThe White Album\tThe Beatles",
            "303\tAbbey Road\tThe Beatles",
            "302\tPet Sounds\tThe Beach Boys",
            "301\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "300\tRevolver\tThe Beatles",
            "299\tThe Band\tThe Band",
            "298\tLed Zeppelin II\tLed Zeppelin",
            "297\tLed Zeppelin IV\tLed Zeppelin",
            "296\tAstral Weeks\tVan Morrison",
            "295\tNevermind\tNirvana",
            "294\tAppetite for Destruction\tGuns N' Roses",
            "293\tThe Joshua Tree\tU2",
            "292\tExile on Main St.\tThe Rolling Stones",
            "291\tHighway 61 Revisited\tBob Dylan",
            "290\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "289\tBorn to Run\tBruce Springsteen",
            "288\tAre You Experienced\tThe Jimi Hendrix Experience",
            "287\tRubber Soul\tThe Beatles",
            "286\tLondon Calling\tThe Clash",
            "285\tRevolver\tThe Beatles",
            "284\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "283\tPet Sounds\tThe Beach Boys",
            "282\tThe Dark Side of the Moon\tPink Floyd",
            "281\tAbbey Road\tThe Beatles",
            "280\tThe White Album\tThe Beatles",
            "279\tThriller\tMichael Jackson",
            "278\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "277\tBorn to Run\tBruce Springsteen",
            "276\tAppetite for Destruction\tGuns N' Roses",
            "275\tLondon Calling\tThe Clash",
            "274\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "273\tExile on Main St.\tThe Rolling Stones",
            "272\tHighway 61 Revisited\tBob Dylan",
            "271\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "270\tAre You Experienced\tThe Jimi Hendrix Experience",
            "269\tRubber Soul\tThe Beatles",
            "268\tRevolver\tThe Beatles",
            "267\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "266\tPet Sounds\tThe Beach Boys",
            "265\tThe Dark Side of the Moon\tPink Floyd",
            "264\tAbbey Road\tThe Beatles",
            "263\tThe White Album\tThe Beatles",
            "262\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "261\tBorn to Run\tBruce Springsteen",
            "260\tAppetite for Destruction\tGuns N' Roses",
            "259\tLondon Calling\tThe Clash",
            "258\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "257\tExile on Main St.\tThe Rolling Stones",
            "256\tHighway 61 Revisited\tBob Dylan",
            "255\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "254\tAre You Experienced\tThe Jimi Hendrix Experience",
            "253\tRubber Soul\tThe Beatles",
            "252\tRevolver\tThe Beatles",
            "251\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "250\tPet Sounds\tThe Beach Boys",
            "249\tThe Dark Side of the Moon\tPink Floyd",
            "248\tAbbey Road\tThe Beatles",
            "247\tThe White Album\tThe Beatles",
            "246\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "245\tBorn to Run\tBruce Springsteen",
            "244\tAppetite for Destruction\tGuns N' Roses",
            "243\tLondon Calling\tThe Clash",
            "242\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "241\tExile on Main St.\tThe Rolling Stones",
            "240\tHighway 61 Revisited\tBob Dylan",
            "239\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "238\tAre You Experienced\tThe Jimi Hendrix Experience",
            "237\tRubber Soul\tThe Beatles",
            "236\tRevolver\tThe Beatles",
            "235\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "234\tPet Sounds\tThe Beach Boys",
            "233\tThe Dark Side of the Moon\tPink Floyd",
            "232\tAbbey Road\tThe Beatles",
            "231\tThe White Album\tThe Beatles",
            "230\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "229\tBorn to Run\tBruce Springsteen",
            "228\tAppetite for Destruction\tGuns N' Roses",
            "227\tLondon Calling\tThe Clash",
            "226\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "225\tExile on Main St.\tThe Rolling Stones",
            "224\tHighway 61 Revisited\tBob Dylan",
            "223\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "222\tAre You Experienced\tThe Jimi Hendrix Experience",
            "221\tRubber Soul\tThe Beatles",
            "220\tRevolver\tThe Beatles",
            "219\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "218\tPet Sounds\tThe Beach Boys",
            "217\tThe Dark Side of the Moon\tPink Floyd",
            "216\tAbbey Road\tThe Beatles",
            "215\tThe White Album\tThe Beatles",
            "214\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "213\tBorn to Run\tBruce Springsteen",
            "212\tAppetite for Destruction\tGuns N' Roses",
            "211\tLondon Calling\tThe Clash",
            "210\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "209\tExile on Main St.\tThe Rolling Stones",
            "208\tHighway 61 Revisited\tBob Dylan",
            "207\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "206\tAre You Experienced\tThe Jimi Hendrix Experience",
            "205\tRubber Soul\tThe Beatles",
            "204\tRevolver\tThe Beatles",
            "203\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "202\tPet Sounds\tThe Beach Boys",
            "201\tThe Dark Side of the Moon\tPink Floyd",
            "200\tAbbey Road\tThe Beatles",
            "199\tThe White Album\tThe Beatles",
            "198\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "197\tBorn to Run\tBruce Springsteen",
            "196\tAppetite for Destruction\tGuns N' Roses",
            "195\tLondon Calling\tThe Clash",
            "194\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "193\tExile on Main St.\tThe Rolling Stones",
            "192\tHighway 61 Revisited\tBob Dylan",
            "191\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "190\tAre You Experienced\tThe Jimi Hendrix Experience",
            "189\tRubber Soul\tThe Beatles",
            "188\tRevolver\tThe Beatles",
            "187\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "186\tPet Sounds\tThe Beach Boys",
            "185\tThe Dark Side of the Moon\tPink Floyd",
            "184\tAbbey Road\tThe Beatles",
            "183\tThe White Album\tThe Beatles",
            "182\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "181\tBorn to Run\tBruce Springsteen",
            "180\tAppetite for Destruction\tGuns N' Roses",
            "179\tLondon Calling\tThe Clash",
            "178\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "177\tExile on Main St.\tThe Rolling Stones",
            "176\tHighway 61 Revisited\tBob Dylan",
            "175\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "174\tAre You Experienced\tThe Jimi Hendrix Experience",
            "173\tRubber Soul\tThe Beatles",
            "172\tRevolver\tThe Beatles",
            "171\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "170\tPet Sounds\tThe Beach Boys",
            "169\tThe Dark Side of the Moon\tPink Floyd",
            "168\tAbbey Road\tThe Beatles",
            "167\tThe White Album\tThe Beatles",
            "166\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "165\tBorn to Run\tBruce Springsteen",
            "164\tAppetite for Destruction\tGuns N' Roses",
            "163\tLondon Calling\tThe Clash",
            "162\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "161\tExile on Main St.\tThe Rolling Stones",
            "160\tHighway 61 Revisited\tBob Dylan",
            "159\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "158\tAre You Experienced\tThe Jimi Hendrix Experience",
            "157\tRubber Soul\tThe Beatles",
            "156\tRevolver\tThe Beatles",
            "155\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "154\tPet Sounds\tThe Beach Boys",
            "153\tThe Dark Side of the Moon\tPink Floyd",
            "152\tAbbey Road\tThe Beatles",
            "151\tThe White Album\tThe Beatles",
            "150\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "149\tBorn to Run\tBruce Springsteen",
            "148\tAppetite for Destruction\tGuns N' Roses",
            "147\tLondon Calling\tThe Clash",
            "146\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "145\tExile on Main St.\tThe Rolling Stones",
            "144\tHighway 61 Revisited\tBob Dylan",
            "143\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "142\tAre You Experienced\tThe Jimi Hendrix Experience",
            "141\tRubber Soul\tThe Beatles",
            "140\tRevolver\tThe Beatles",
            "139\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "138\tPet Sounds\tThe Beach Boys",
            "137\tThe Dark Side of the Moon\tPink Floyd",
            "136\tAbbey Road\tThe Beatles",
            "135\tThe White Album\tThe Beatles",
            "134\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "133\tBorn to Run\tBruce Springsteen",
            "132\tAppetite for Destruction\tGuns N' Roses",
            "131\tLondon Calling\tThe Clash",
            "130\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "129\tExile on Main St.\tThe Rolling Stones",
            "128\tHighway 61 Revisited\tBob Dylan",
            "127\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "126\tAre You Experienced\tThe Jimi Hendrix Experience",
            "125\tRubber Soul\tThe Beatles",
            "124\tRevolver\tThe Beatles",
            "123\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "122\tPet Sounds\tThe Beach Boys",
            "121\tThe Dark Side of the Moon\tPink Floyd",
            "120\tAbbey Road\tThe Beatles",
            "119\tThe White Album\tThe Beatles",
            "118\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "117\tBorn to Run\tBruce Springsteen",
            "116\tAppetite for Destruction\tGuns N' Roses",
            "115\tLondon Calling\tThe Clash",
            "114\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "113\tExile on Main St.\tThe Rolling Stones",
            "112\tHighway 61 Revisited\tBob Dylan",
            "111\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "110\tAre You Experienced\tThe Jimi Hendrix Experience",
            "109\tRubber Soul\tThe Beatles",
            "108\tRevolver\tThe Beatles",
            "107\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "106\tPet Sounds\tThe Beach Boys",
            "105\tThe Dark Side of the Moon\tPink Floyd",
            "104\tAbbey Road\tThe Beatles",
            "103\tThe White Album\tThe Beatles",
            "102\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "101\tBorn to Run\tBruce Springsteen",
            "100\tAppetite for Destruction\tGuns N' Roses",
            "99\tLondon Calling\tThe Clash",
            "98\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "97\tExile on Main St.\tThe Rolling Stones",
            "96\tHighway 61 Revisited\tBob Dylan",
            "95\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "94\tAre You Experienced\tThe Jimi Hendrix Experience",
            "93\tRubber Soul\tThe Beatles",
            "92\tRevolver\tThe Beatles",
            "91\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "90\tPet Sounds\tThe Beach Boys",
            "89\tThe Dark Side of the Moon\tPink Floyd",
            "88\tAbbey Road\tThe Beatles",
            "87\tThe White Album\tThe Beatles",
            "86\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "85\tBorn to Run\tBruce Springsteen",
            "84\tAppetite for Destruction\tGuns N' Roses",
            "83\tLondon Calling\tThe Clash",
            "82\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "81\tExile on Main St.\tThe Rolling Stones",
            "80\tHighway 61 Revisited\tBob Dylan",
            "79\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "78\tAre You Experienced\tThe Jimi Hendrix Experience",
            "77\tRubber Soul\tThe Beatles",
            "76\tRevolver\tThe Beatles",
            "75\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "74\tPet Sounds\tThe Beach Boys",
            "73\tThe Dark Side of the Moon\tPink Floyd",
            "72\tAbbey Road\tThe Beatles",
            "71\tThe White Album\tThe Beatles",
            "70\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "69\tBorn to Run\tBruce Springsteen",
            "68\tAppetite for Destruction\tGuns N' Roses",
            "67\tLondon Calling\tThe Clash",
            "66\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "65\tExile on Main St.\tThe Rolling Stones",
            "64\tHighway 61 Revisited\tBob Dylan",
            "63\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "62\tAre You Experienced\tThe Jimi Hendrix Experience",
            "61\tRubber Soul\tThe Beatles",
            "60\tRevolver\tThe Beatles",
            "59\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "58\tPet Sounds\tThe Beach Boys",
            "57\tThe Dark Side of the Moon\tPink Floyd",
            "56\tAbbey Road\tThe Beatles",
            "55\tThe White Album\tThe Beatles",
            "54\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "53\tBorn to Run\tBruce Springsteen",
            "52\tAppetite for Destruction\tGuns N' Roses",
            "51\tLondon Calling\tThe Clash",
            "50\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "49\tExile on Main St.\tThe Rolling Stones",
            "48\tHighway 61 Revisited\tBob Dylan",
            "47\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "46\tAre You Experienced\tThe Jimi Hendrix Experience",
            "45\tRubber Soul\tThe Beatles",
            "44\tRevolver\tThe Beatles",
            "43\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "42\tPet Sounds\tThe Beach Boys",
            "41\tThe Dark Side of the Moon\tPink Floyd",
            "40\tAbbey Road\tThe Beatles",
            "39\tThe White Album\tThe Beatles",
            "38\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "37\tBorn to Run\tBruce Springsteen",
            "36\tAppetite for Destruction\tGuns N' Roses",
            "35\tLondon Calling\tThe Clash",
            "34\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "33\tExile on Main St.\tThe Rolling Stones",
            "32\tHighway 61 Revisited\tBob Dylan",
            "31\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "30\tAre You Experienced\tThe Jimi Hendrix Experience",
            "29\tRubber Soul\tThe Beatles",
            "28\tRevolver\tThe Beatles",
            "27\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "26\tPet Sounds\tThe Beach Boys",
            "25\tThe Dark Side of the Moon\tPink Floyd",
            "24\tAbbey Road\tThe Beatles",
            "23\tThe White Album\tThe Beatles",
            "22\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "21\tBorn to Run\tBruce Springsteen",
            "20\tAppetite for Destruction\tGuns N' Roses",
            "19\tLondon Calling\tThe Clash",
            "18\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "17\tExile on Main St.\tThe Rolling Stones",
            "16\tHighway 61 Revisited\tBob Dylan",
            "15\tThe Velvet Underground & Nico\tThe Velvet Underground",
            "14\tAre You Experienced\tThe Jimi Hendrix Experience",
            "13\tRubber Soul\tThe Beatles",
            "12\tRevolver\tThe Beatles",
            "11\tSgt. Pepper's Lonely Hearts Club Band\tThe Beatles",
            "10\tPet Sounds\tThe Beach Boys",
            "9\tThe Dark Side of the Moon\tPink Floyd",
            "8\tAbbey Road\tThe Beatles",
            "7\tThe White Album\tThe Beatles",
            "6\tNever Mind the Bollocks Here's the Sex Pistols\tSex Pistols",
            "5\tBorn to Run\tBruce Springsteen",
            "4\tAppetite for Destruction\tGuns N' Roses",
            "3\tLondon Calling\tThe Clash",
            "2\tThe Rise and Fall of Ziggy Stardust and the Spiders From Mars\tDavid Bowie",
            "1\tExile on Main St.\tThe Rolling Stones"
        ]
            
    ]
};
  
    var ul = document.createElement('ul');
    var button = document.getElementById('option-buttons');
  
    for (var i = 0; i < items.length; i++) {
      var li = document.createElement('li');
      li.textContent = items[i];
      ul.appendChild(li);
    }
  
    button.appendChild(ul);
    button.style.display = 'block';
  
  